version: "3.4"
services:
  easyrelease:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../../build:/easyrelease/build/"
      - "../../node_modules:/easyrelease/node_modules/"
      - "../../config:/easyrelease/config/"
      - "../../package.json:/easyrelease/package.json"
      - "../../package.lock:/easyrelease/package.lock"
      - "${CONFIG_PATH}:${CONFIG_DIR_DEST}"
    env_file:
      - "./.env"
    #command: ["easyrelease", "--verbose", "--configurationFilePath=${CONFIG_DIR_DEST}", "--profile=${PROFILE}", "--currentWorkDirectory=${REPO_DIR_NAME}"]
    command: bash
