const enum InternalType {
  MERGE_REQUEST = '__MERGE_REQUEST',
  PULL_REQUEST = '__PULL_REQUEST',
  GITHUB_COMMIT = '__GITHUB_COMMIT',
  GITLAB_COMMIT = '__GITLAB_COMMIT',
  GITLAB_USER = '__GITLAB_USER',
  GITHUB_USER = '__GITHUB_USER',
  GITHUB_ISSUE = '__GITHUB_ISSUE',
  GITLAB_ISSUE = '__GITLAB_ISSUE',
  GITLAB_LABEL = '__GITLAB_LABEL',
  GITHUB_LABEL = '__GITHUB_LABEL',
  CHERRY_PICK = '__CHERRY_PICK',
}

export default InternalType;
